app ha already been declared within try/catch
