app has already been declared within try/catch
